#!/usr/bin/env sh

version () {
	echo "csaa.ds git handy v0.0.0";
	echo
}

usage() {
    echo "usage: git handy branchName"
    echo
}


main() {
    if [ "$#" -lt 1 ]; then
        usage; exit 1
    fi

    local subcommand="$1"; shift

    case $subcommand in
        "-h"|"--help")
            usage; exit 0
            ;;
        "-v"|"--version")
            version; exit 0
            ;;
    esac
}