#!/usr/bin/env sh

version() {
	echo "csaa.ds git handy v1.0.1";
	echo
}

usage() {
	echo "usage: git handy branchName"
	echo
}

gitSync() {
	git stash;
	DEFAULT_BRANCH=$(findDefaultBranch);

	git checkout $DEFAULT_BRANCH;
	git fetch;
	git merge;
	git checkout -b $1;
	git stash pop;
}

findDefaultBranch() {
	echo `git for-each-ref --sort=-committerdate --format='%(upstream:short)' | head | grep -o '\w*$'`
}

main() {
	if [ "$#" -lt 1 ]; then
		usage; exit 1
	fi

	local subcommand="$1"; shift

	case $subcommand in
		"-h"|"--help")
			usage; exit 0
			;;
		"-v"|"--version")
			version; exit 0
			;;
	esac

	gitSync $subcommand;

}

main "$@";
